### ISSUE TITLE
Dry run or ability to check if the commit history is valid?

### ISSUE THREAD

**Issue by pcarranzav** [resin-io/versionist#62]
It would be nice to have a way to run something like `versionist --check` or `versionist --dry-run` to see if the commit history since the recent version is valid.
That way users of this tool could integrate that to CI tests on PRs, so that invalid commit messages are caught before PRs are merged.

**Comment by lurch** [comment]
What would count as an "invalid commit message"?
Although I agree a "dry run" mode would be nice - effectively a command-line-override forcing both https://github.com/resin-io/versionist#editchangelog-boolean and https://github.com/resin-io/versionist#editversion-boolean to `false`.

I think what you're asking for is actually part of the PR-linting bot that @hedss is going to be working on?

**Comment by hedss** [comment]
@pcarranzav We're actually in the process of defining some bots whose sole purpose is:

* On initial opening of a PR, ensure that there is at least one commit message that details the changes and ensures that a valid version up is occuring (be it patch, minor or major), and ensure that code lints correctly
* On a merge (where all pre-reqs are correct), the version of `CHANGELOG.md` and `package.json` is upped based on the commits from the PR, and then commits these, adds a tag of the new version and then pushes the lot to `master` (I'm currently working on the tooling for this atm)

I think these cover those issues?

**Comment by pcarranzav** [comment]
@hedss yeah, I think that would definitely cover the issues.
I still think a `--dry-run` would be useful though, something like what @lurch said - that way you can check on your local tree to see if you're doing it right before pushing.

**Comment by craig-mulligan** [comment]
+1 for dry run

**Comment by hedss** [comment]
So essentially it outputs to `stdout` the changes it'd make in the files.

I'd say in that case, it might also be useful to have `--dry-run` as a parameter taking option, with two possible strings, `changes` and `full` (?). This would allow you to either see just the extra text being added to altered files, or full copies of the files themselves.

**Comment by craig-mulligan** [comment]
Hmm, how about always showing full with the changes in green kinda like a `git diff`.

**Comment by lekkas** [comment]
This loosely connects to #65 , which reflects the current state of versionist, where if no version incrementing commits are found, running `versionist` fails spectacularly.

I'm +1 on having a dry run option for maintainers that want to integrate `versionist` in their CI process along with code linting and test framework running, since it doesn't really affect the soon-to-be requirement of having a bot/github webhook to check version/changelog conventions. 

By the way, the reason why we want to have a versionist bot is to have a single 'truth' of required commit/PR conventions and avoid relying on each project's installed `versionist` package, that would require  pinging every maintainer to update `versionist` every time a new version is released (which I expect to happen frequently in the beginning). Note that `versionist` is language agnostic and will also run in non-node projects, so package.json/semver will not always be an option for fetching new versions.

I'd be fine with just printing the diff in stdout (`git diff`) style and exit the process with 0, to keep things as simple as possible and avoid adding any extra options in `--dry-run`. Printing the full changelog will probably be inconvenient for projects with many entries (see supervisor), but in any case, I don't feel strongly about this. In case of missing version incrementing commits it should fail with an error code (also see #65)

**Comment by craig-mulligan** [comment]
Closing this, we now have `--dry` flag to run without updating the changelog. Feel free to reopen if there is anything more to address.
